# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/140v_LlL6ZYB90YUzM2XmhoZy7U2wcdyr
"""

import pandas as pd
from statsmodels.stats import weightstats as stests

df=pd.read_csv("/content/diabetes.csv")

df.head()

df[["Glucose","BloodPressure"]].describe()

ztest ,pvalue = stests.ztest(df['Glucose'], x2=None, value=146)
print(float(pvalue))
print(ztest)

if pvalue<0.05:
    print("Null hyphothesis rejected , Alternative hyphothesis accepted")
else:
    print("Null hyphothesis accepted , Alternative hyphothesis rejected")

